import Link from "next/link";
import { notFound } from "next/navigation";
import { addRentTermAction, createOneOffChargeAction, recordExpenseAction } from "@/lib/actions";
import { getPropertyDetail } from "@/lib/data";
import { todayIso } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { Flash, flashFrom } from "@/components/flash";

export default async function PropertyDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {id}=await params; const [detail,flash]=await Promise.all([getPropertyDetail(id),flashFrom(searchParams)]); if(!detail) notFound();
  const {property,units,leases,payments,expenses,ytdNetCents}=detail;
  return <>
    <div className="page-head"><div><div className="eyebrow">Property detail</div><h1>{property.address_line1}</h1><p>{property.city}, {property.region} {property.postal_code}</p></div><div className="actions"><Link className="button" href={`/payments/new?propertyId=${property.id}`}>Record payment</Link><Link className="button secondary" href={`/properties/${property.id}/lease/new`}>Create lease</Link><Link className="button secondary" href="/properties">All properties</Link></div></div><Flash {...flash}/>
    <div className="grid cols-3" style={{marginBottom:20}}><section className="card"><div className="eyebrow">YTD net</div><div className="metric">{formatMoney(ytdNetCents)}</div></section><section className="card"><div className="eyebrow">Units</div><div className="metric">{units.filter(u=>!u.deleted_at).length}</div></section><section className="card"><div className="eyebrow">Current lease</div><div className="metric" style={{fontSize:22}}>{leases.find(l=>l.status==='active')?.tenant_name??'None'}</div></section></div>
    <div className="subnav"><a href="#leases">Units & leases</a><a href="#payments">Payments</a><a href="#expenses">Expenses</a><a href="#add-entry">Add entry</a></div>
    <section id="leases" className="card" style={{marginBottom:20}}><h2 style={{marginTop:0}}>Units and current leases</h2>{units.map(unit=>{const lease=leases.find(l=>l.unit_id===unit.id&&l.status==='active');return <div className="list-card" key={unit.id} style={{padding:'12px 0',borderBottom:'1px solid var(--line)'}}><div><strong>{unit.name}</strong><div className="muted">{lease?`${lease.tenant_name??'No primary tenant'} · started ${lease.start_date}`:'No active lease'}</div></div><div className="amount">{lease?.rent_cents?`${formatMoney(lease.rent_cents)}/month`:'—'}</div></div>})}</section>
    <div className="grid cols-2">
      <section id="payments" className="card"><h2 style={{marginTop:0}}>Recent payments</h2>{payments.length===0?<p className="muted">No payments recorded.</p>:<div className="stack">{payments.slice(0,8).map(payment=><div className="list-card" key={payment.id}><div><strong>{payment.payer_name}</strong><div className="muted">{payment.received_date} · {payment.method}</div></div><div className={`amount ${payment.amount_cents<0?'danger-text':'success'}`}>{formatMoney(payment.amount_cents)}</div></div>)}</div>}</section>
      <section id="expenses" className="card"><h2 style={{marginTop:0}}>Recent expenses</h2>{expenses.length===0?<p className="muted">No expenses recorded.</p>:<div className="stack">{expenses.slice(0,8).map(expense=><div className="list-card" key={expense.id}><div><strong>{expense.category}</strong><div className="muted">{expense.expense_date} · {expense.description}{expense.receipt_blob_url&&<> · <a className="link" href={`/api/receipts/${expense.id}`}>Receipt</a></>}</div></div><div className={`amount ${expense.amount_cents<0?'success':'danger-text'}`}>{formatMoney(expense.amount_cents)}</div></div>)}</div>}</section>
    </div>
    <section style={{marginTop:24}}><div className="page-head"><div><h2 style={{margin:0}}>Rent history</h2><p>A rent increase adds a new effective-dated term. It never overwrites prior rent.</p></div></div>{leases.filter(lease=>lease.status==='active').map(lease=><form className="card form" action={addRentTermAction} key={lease.lease_id} style={{marginBottom:16}}><input type="hidden" name="propertyId" value={property.id}/><input type="hidden" name="leaseId" value={lease.lease_id}/><div><strong>{lease.unit_name} — {lease.tenant_name??'No tenant'}</strong><div className="muted">Current rent: {lease.rent_cents?formatMoney(lease.rent_cents):'not set'}</div></div><div className="form-row"><div className="field"><label>New rent</label><input name="rent" inputMode="decimal" required/></div><div className="field"><label>Effective from</label><input name="effectiveFrom" type="date" required/></div></div><div className="form-row"><div className="field"><label>Due day</label><input name="dueDay" type="number" min="1" max="28" defaultValue={lease.due_day} required/></div><div className="field"><label>Reason</label><input name="reason" placeholder="Annual increase" required/></div></div><button className="button secondary" type="submit">Add dated rent term</button></form>)}</section>
    <section id="add-entry" style={{marginTop:24}}><div className="page-head"><div><h2 style={{margin:0}}>Add a property entry</h2><p>Posted entries are immutable. Corrections require a visible reversal.</p></div></div><div className="grid cols-2">
      <form className="card form" action={recordExpenseAction}><h3 style={{margin:0}}>Record expense</h3><input type="hidden" name="propertyId" value={property.id}/><div className="field"><label>Unit</label><select name="unitId"><option value="">Whole property</option>{units.filter(u=>!u.deleted_at).map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></div><div className="form-row"><div className="field"><label>Category</label><input name="category" required/></div><div className="field"><label>Date</label><input name="expenseDate" type="date" defaultValue={todayIso()} required/></div></div><div className="field"><label>Description</label><input name="description" required/></div><div className="form-row"><div className="field"><label>Amount</label><input name="amount" inputMode="decimal" required/></div><div className="field"><label>Vendor</label><input name="vendor"/></div></div><div className="field"><label>Receipt image or PDF</label><input name="receipt" type="file" accept="image/*,application/pdf"/><small>Optional, up to 4 MB. Stored privately in Vercel Blob.</small></div><button className="button" type="submit">Post expense</button></form>
      <form className="card form" action={createOneOffChargeAction}><h3 style={{margin:0}}>Record one-off charge</h3><input type="hidden" name="propertyId" value={property.id}/><div className="form-row"><div className="field"><label>Unit</label><select name="unitId"><option value="">Whole property</option>{units.filter(u=>!u.deleted_at).map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></div><div className="field"><label>Tenant</label><select name="tenantId"><option value="">Unassigned</option>{leases.filter(l=>l.tenant_id).map(l=><option value={l.tenant_id!} key={l.tenant_id!}>{l.tenant_name}</option>)}</select></div></div><div className="field"><label>Type</label><select name="chargeType"><option value="late_fee">Late fee</option><option value="repair_chargeback">Repair chargeback</option><option value="adjustment">Adjustment</option></select></div><div className="field"><label>Description</label><input name="description" required/></div><div className="form-row"><div className="field"><label>Amount</label><input name="amount" inputMode="decimal" required/></div><div className="field"><label>Due date</label><input name="dueDate" type="date" defaultValue={todayIso()} required/></div></div><input type="hidden" name="effectiveDate" value={todayIso()}/><button className="button" type="submit">Post charge</button></form>
    </div></section>
  </>;
}
