import { getFilterOptions, getLedger } from "@/lib/data";
import { reverseFinancialEntryAction } from "@/lib/actions";
import { formatMoney } from "@/lib/money";
import { todayIso } from "@/lib/dates";
import { Flash, flashFrom } from "@/components/flash";

export default async function LedgerPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const params=await searchParams; const pick=(key:string)=>typeof params[key]==='string'?params[key] as string:undefined;
  const filters={propertyId:pick('propertyId'),tenantId:pick('tenantId'),from:pick('from'),to:pick('to')};
  const [entries,options,flash]=await Promise.all([getLedger(filters),getFilterOptions(),flashFrom(Promise.resolve(params))]);
  const exportQuery=new URLSearchParams(Object.entries(filters).filter(([,v])=>v).map(([k,v])=>[k,v!])).toString();
  return <><div className="page-head"><div><div className="eyebrow">Immutable chronology</div><h1>Ledger</h1><p>Charges and expenses are positive; payments are shown as negative against the balance.</p></div><div className="actions"><a className="button secondary" href={`/api/export/csv${exportQuery?`?${exportQuery}`:''}`}>Full CSV dump</a><a className="button" href="/api/export/json">Full JSON dump</a></div></div><Flash {...flash}/>
    <form className="card form" method="get" style={{marginBottom:20}}><div className="form-row"><div className="field"><label>Property</label><select name="propertyId" defaultValue={filters.propertyId??''}><option value="">All properties</option>{options.properties.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></div><div className="field"><label>Tenant</label><select name="tenantId" defaultValue={filters.tenantId??''}><option value="">All tenants</option>{options.tenants.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></div></div><div className="form-row"><div className="field"><label>From</label><input name="from" type="date" defaultValue={filters.from}/></div><div className="field"><label>Through</label><input name="to" type="date" defaultValue={filters.to}/></div></div><div className="actions"><button className="button" type="submit">Apply filters</button><a className="button secondary" href="/ledger">Clear</a></div></form>
    <div className="table-wrap">{entries.length===0?<div className="empty">No ledger entries match these filters.</div>:<table><thead><tr><th>Date</th><th>Type</th><th>Property</th><th>Tenant</th><th>Description</th><th>Amount</th><th>Correction</th></tr></thead><tbody>{entries.map(entry=><tr className={`ledger-${entry.entry_type}`} key={`${entry.entry_type}:${entry.id}`}><td>{entry.entry_date}</td><td><span className="pill">{entry.entry_type}</span></td><td>{entry.property_address}</td><td>{entry.tenant_name??'—'}</td><td>{entry.description}</td><td className="amount">{formatMoney(entry.amount_cents)}</td><td>{!entry.description.startsWith('Reversal')&&<details className="destructive"><summary>Reverse</summary><form className="form" action={reverseFinancialEntryAction} style={{minWidth:300}}>{(()=>{const expected=`REVERSE ${entry.entry_type.toUpperCase()} ${entry.id.slice(0,8)}`;return <><input type="hidden" name="entryType" value={entry.entry_type}/><input type="hidden" name="entryId" value={entry.id}/><input type="hidden" name="expectedConfirmation" value={expected}/><div className="field"><label>Reason</label><input name="reason" minLength={5} required/></div><div className="field"><label>Reversal date</label><input name="reversalDate" type="date" defaultValue={todayIso()} required/></div><div className="field"><label>Type “{expected}”</label><input name="confirmation" required/></div><button className="button danger" type="submit">Create reversing {entry.entry_type}</button></>})()}</form></details>}</td></tr>)}</tbody></table>}</div>
  </>;
}
