import Link from "next/link";
import { notFound } from "next/navigation";
import { createLeaseAction } from "@/lib/actions";
import { getFilterOptions, getPropertyDetail } from "@/lib/data";
import { todayIso } from "@/lib/dates";
import { Flash, flashFrom } from "@/components/flash";

export default async function NewLeasePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {id}=await params; const [detail,filters,flash]=await Promise.all([getPropertyDetail(id),getFilterOptions(),flashFrom(searchParams)]); if(!detail) notFound();
  const available=detail.units.filter(unit=>!unit.deleted_at&&!detail.leases.some(lease=>lease.unit_id===unit.id&&lease.status==='active'));
  return <><div className="page-head"><div><div className="eyebrow">Tenant and rent setup</div><h1>Create lease</h1><p>{detail.property.address_line1}. Rent changes later become new dated terms.</p></div><Link className="button secondary" href={`/properties/${id}`}>Cancel</Link></div><Flash {...flash}/>{available.length===0?<div className="card empty">Every active unit already has an active lease.</div>:<form className="card form" action={createLeaseAction}><input type="hidden" name="propertyId" value={id}/><div className="field"><label htmlFor="unitId">Unit</label><select id="unitId" name="unitId">{available.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></div><div className="field"><label htmlFor="tenantId">Existing tenant</label><select id="tenantId" name="tenantId"><option value="">Create a new tenant below</option>{filters.tenants.map(tenant=><option key={tenant.id} value={tenant.id}>{tenant.label}</option>)}</select><small>Reusing a tenant preserves their history across leases.</small></div><div className="form-row"><div className="field"><label htmlFor="tenantName">New tenant name</label><input id="tenantName" name="tenantName"/><small>Required only when no existing tenant is selected.</small></div><div className="field"><label htmlFor="tenantEmail">New tenant email</label><input id="tenantEmail" name="tenantEmail" type="email"/></div></div><div className="field"><label htmlFor="tenantPhone">New tenant phone</label><input id="tenantPhone" name="tenantPhone" type="tel"/></div><div className="form-row"><div className="field"><label htmlFor="startDate">Start date</label><input id="startDate" name="startDate" type="date" defaultValue={todayIso()} required/></div><div className="field"><label htmlFor="endDate">End date</label><input id="endDate" name="endDate" type="date"/></div></div><div className="form-row"><div className="field"><label htmlFor="rent">Monthly rent</label><input id="rent" name="rent" inputMode="decimal" required/></div><div className="field"><label htmlFor="dueDay">Due day</label><input id="dueDay" name="dueDay" type="number" min="1" max="28" defaultValue="1" required/></div></div><div className="field"><label htmlFor="deposit">Contractual deposit</label><input id="deposit" name="deposit" inputMode="decimal" defaultValue="0.00" required/><small>This records the lease term only; v1 does not perform deposit accounting.</small></div><div className="field"><label htmlFor="notes">Notes</label><textarea id="notes" name="notes"/></div><button className="button" type="submit">Create tenant and lease</button></form>}</>;
}
